test1 = Test.create(name: "Sign Up Quiz")
test2 = Test.create(name: "New Entry Quiz")
signUpQuestion1 = Question.create(content: "Which can you most relate to?", test_id: 1)
signUpQuestion2 = Question.create(content: "Which can you most relate to?", test_id: 1)
newEntryQuestion1 = Question.create(content: "Which closest describes how you feel today?", test_id: 2)
newEntryQuestion2 = Question.create(content: "Which do you need most right now?", test_id: 2)
signUpQuestion1Answer1 = Answer.create(question_id: 1, content: "Some days I can't bother dealing with the world and/or the people in it", score: 1)
signUpQuestion1Answer2 = Answer.create(question_id: 1, content: "Sometimes it's just not worth the energy/effort", score: 2)
signUpQuestion1Answer3 = Answer.create(question_id: 1, content: "People say that I fly off the handle easily.", score: 3)
signUpQuestion1Answer4 = Answer.create(question_id: 1, content: "Everyone will betray you in some way, at some point", score: 4)
signUpQuestion2Answer2 = Answer.create(question_id: 2, content: "Many times I feel everything is pointless", score: 2)
signUpQuestion2Answer1 = Answer.create(question_id: 2, content: "I prefer to just stay at home rather than go out and try new things", score: 1)
signUpQuestion2Answer4 = Answer.create(question_id: 2, content: "No one will ever love me", score: 4)
signUpQuestion2Answer3 = Answer.create(question_id: 2, content: "When things don’t go my way, I 'lose it.'", score: 3)
newEntryQuestion1Answer1 = Answer.create(question_id: 3, content: "I don't have the energy to deal with life right now", score: 1)
newEntryQuestion1Answer2 = Answer.create(question_id: 3, content: "There's no point in anything", score: 2)
newEntryQuestion1Answer3 = Answer.create(question_id: 3, content: "I feel like I'm going to explode", score: 3)
newEntryQuestion1Answer4 = Answer.create(question_id: 3, content: "I feel hurt by someone I love/trust", score: 4)
newEntryQuestion2Answer1 = Answer.create(question_id: 4, content: "I need to feel understood", score: 0)
newEntryQuestion2Answer2 = Answer.create(question_id: 4, content: "I need help getting over it", score: 6)
#
kidCudi = Artist.create(name: "Kid Cudi", score: 1, home_photo:"https://i.redd.it/emvjwjgulztz.png", depressed_photo:"https://pbs.twimg.com/media/CymmcOjXAAAPH-z.jpg", angry_photo:"http://20some.com/wp-content/uploads/2017/09/10547824_10152986124308586_6086290500636516698_o.jpg", happy_photo:"https://i1.wp.com/www.rehabonlinemag.com/wp-content/uploads/2016/10/kid-cudi.jpg?fit=1203%2C803", writing_photo:"https://images-na.ssl-images-amazon.com/images/I/B1qVEldBnNS._CR0,0,3840,2880_.png", listen_photo:"http://cdn3.hiphopmyway.com/wp-content/uploads/2015/07/kid-cudi-e1437666314575.jpg")
kanyeWest = Artist.create(name: "Kanye West", score: 3, home_photo:"https://hdwallsource.com/img/2017/4/kanye-west-performing-hd-wallpaper-59575-61362-hd-wallpapers.jpg", depressed_photo:"https://i.imgur.com/8tSWKDe.jpg?1", angry_photo:"http://i.imgur.com/hG0rOzR.jpg", happy_photo:"http://5dwallpaper.com/wp-content/uploads/2017/07/kanye-west-HD-wallpaper-wp3807699.jpg", writing_photo:"http://static.djbooth.net/pics-features/rect/kanye-writing-book-hip-hop.jpg", listen_photo:"http://s3.amazonaws.com/digitaltrends-uploads-prod/2016/01/kanye-west-singer-rapper-musician.jpg")


kidCudi1 = Playlist.create(link: "https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/64l1bmWWPwxIQlwKrE4zbc" , score:1, artist_id:1)
kidCudi2 = Playlist.create(link: "https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/64l1bmWWPwxIQlwKrE4zbc", score:2, artist_id:1)
kidCudi3 = Playlist.create(link: "https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/3yA33O9hOEnsSmsQLj9bxy", score:3, artist_id:1)
kidCudi4 = Playlist.create(link: "https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/0B36MStdBKmpVPyCzaX3N7", score:4, artist_id:1)
kidCudi5 = Playlist.create(link: "https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/7utPqVzsGofMs8YpkgdjPE", score:5, artist_id:1)
kanyeWest1 = Playlist.create(link:"https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/0k2TcOFTTwXFBmjilLEZgL", score:1, artist_id:2)
kanyeWest2 = Playlist.create(link:"https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/0k2TcOFTTwXFBmjilLEZgL", score:2, artist_id:2)
kanyeWest3 = Playlist.create(link: "https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/4T2tUV6gRaCslNdTJPGMfB", score:3, artist_id:2)
kanyeWest4 = Playlist.create(link:"https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/476xtomUj0d0Wasqay3Gjd", score:4, artist_id:2)
kanyeWest5 = Playlist.create(link:"https://open.spotify.com/embed/user/cstvtprkn23yelai6ikhucj6t/playlist/3jWysONYFNR7JfLDLKmmmO", score:5, artist_id:2)
