# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

CLIENT_ID: "41e6d53b8d3d4b67949aa7b8212cb4d3"
CLIENT_SECRET: "666cd2ecbd2c46feaa56ecdc09b2dd75"
REDIRECT_URI: "http://localhost:3001/auth"
SCOPES: "user-library-read user-library-modify user-top-read user-modify-playback-state playlist-modify-public playlist-modify-private"
SECRET: "UthoughtUwereDaBessMinusNowwww"
SECURITY_CODE: 'HS256'
